plugins {
    id 'java'
    id 'com.gradleup.shadow' version '8.3.0'
    id("xyz.jpenilla.run-paper") version "2.3.1"
    id 'com.github.johnrengelman.shadow' version '8.1.1'
    id 'org.jetbrains.kotlin.jvm'
}

group = 'studio.awel'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
    maven { url 'https://repo.codemc.io/repository/maven-snapshots/' }

    maven {
        name = "spigotmc-repo"
        url = "https://hub.spigotmc.org/nexus/content/repositories/snapshots/"
    }
    maven {
        name = "sonatype"
        url = "https://oss.sonatype.org/content/groups/public/"
    }
    maven {
        url = 'https://repo.extendedclip.com/content/repositories/placeholderapi/'
    }
    maven {
        url 'https://jitpack.io'
    }
    maven { url = "https://repo.aikar.co/content/groups/aikar/" }
}

dependencies {
    compileOnly("org.spigotmc:spigot-api:1.21.4-R0.1-SNAPSHOT")
    implementation 'com.samjakob:SpiGUI:1.4.1'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.13.4'
    compileOnly 'me.clip:placeholderapi:2.11.5'
    compileOnly "com.github.MilkBowl:VaultAPI:1.7"
    implementation "co.aikar:acf-paper:0.5.1-SNAPSHOT"
    implementation "org.yaml:snakeyaml:1.28"
    implementation 'space.arim.dazzleconf:dazzleconf-core:1.2.1'
    implementation 'space.arim.dazzleconf:dazzleconf-ext-snakeyaml:1.2.1'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"

    implementation 'net.wesjd:anvilgui:1.10.5-SNAPSHOT'

}

shadowJar {
    relocate 'org.yaml.snakeyaml', 'studio.awel.xCasinos.shaded.snakeyaml'
    relocate 'net.wesjd.anvilgui', 'studio.awel.xCasinos.anvilgui'
    relocate"space.arim.dazzleconf", "studio.awel.xCasinos.libs.dazzleconf"
    archiveClassifier.set('')
}
build.dependsOn(shadowJar)

tasks {
    runServer {
        // Configure the Minecraft version for our task.
        // This is the only required configuration besides applying the plugin.
        // Your plugin's jar (or shadowJar if present) will be used automatically.
        minecraftVersion("1.21")
    }
}

def targetJavaVersion = 21
java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'

    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        options.release.set(targetJavaVersion)
    }
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('plugin.yml') {
        expand props
    }
}

artifacts {
    archives shadowJar
}
kotlin {
    jvmToolchain(21)
}
